# Generated by Django 4.2.5 on 2023-09-19 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_alter_train_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["number"]},
        ),
    ]
