# Generated by Django 4.2.5 on 2023-09-19 21:35

from django.db import migrations, models
import station.upload_to_path


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_alter_crew_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=station.upload_to_path.UploadToPath('journey-images/')),
        ),
    ]
